### ISSUE TITLE
Shaded jar causing problems with slf4j

### ISSUE THREAD

**Issue by mattcopas** [thomasjungblut/glove#2]
We are currently having issues with this library due to a conflict between slf4j bindings. We have tried excluding slf4j from glove in our pom, however this isn't possible because glove is a shaded jar.

Would it be possible for you to upload a non-shaded jar to Maven for us to use?

Many thanks

**Comment by thomasjungblut** [comment]
Sure, I take a look on the weekend. You just need the pure jar, not the fat jar right?

**Comment by mattcopas** [comment]
Yes please!

Cheers

**Comment by thomasjungblut** [comment]
Just published 0.2, should take some time to be available on the maven search though.
I split the jars into two:
https://github.com/thomasjungblut/glove/blob/master/pom.xml#L161

The fat jar now has the classifier:
> <classifier>jar-with-dependencies</classifier>

so the "normal" 0.2 artifact should give you the 31K source only version.

Let me know if you have any trouble!

**Comment by mattcopas** [comment]
That's working fine now. Will close issue - thanks
